apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-cloudflaretunnel-pv
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  persistentVolumeReclaimPolicy: Retain
  csi:
    driver: driver.longhorn.io
    fsType: ext4
    volumeHandle: longhorn-cloudflaretunnel-pv
