apiVersion: v1
kind: PersistentVolume
metadata:
  name: longhorn-volv-pvctest
  namespace: fluxtest
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 1Gi